---

- name: Fail if required Collabora settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - collabora_online_hostname
    - collabora_online_uid
    - collabora_online_gid
    - collabora_online_container_network
    - collabora_online_env_variable_password
    - collabora_online_aliasgroup

- when: collabora_online_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Collabora Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - collabora_online_container_labels_traefik_hostname
        - collabora_online_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `collabora_online_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if collabora_online_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          collabora_online_container_labels_traefik_path_prefix (`{{ collabora_online_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/collabora`).
      when: "collabora_online_container_labels_traefik_path_prefix != '/' and collabora_online_container_labels_traefik_path_prefix[-1] == '/'"

    - name: Fail if collabora_online_container_labels_traefik_path_prefix is not /
      ansible.builtin.fail:
        msg: >-
          Using `collabora_online_container_labels_traefik_path_prefix` (`{{ collabora_online_container_labels_traefik_path_prefix }}`)
          other than `/` is not supported right now.
      when: "collabora_online_container_labels_traefik_path_prefix != '/'"
